### PR TITLE
Campaign Member Support template

### LINKED ISSUE #192: Return Campaign memberSupport template when available
When a member texts a QUESTION keyword, we send a `supportRequested` template defined in code regardless of the campaign they're in.

Ideally if the Conversation has a Campaign set, Gambit should send the `memberSupport` template defined on the Campaign instead of the default.

### PR DESCRIPTION
**Pull request by aaronschachter**
Closes #192 

Test: Run Consolebot with a new user.
* Send Q - verify the hardcoded `memberSupportRequested` message is returned
* Send a keyword, e.g. `tuskbot`
* Send Q - verify the Campaign's `memberSupport` template is returned

### CODE REVIEW

**Comment by rapala61** [comment]
@aaronschachter  I didn't fully understand the directions to test, but I'll paste my messages here so you can check if this looks good:

```
{
  "_id": ObjectId("59f76cd2b7a2df9cd263eae3"),
  "updatedAt": ISODate("2017-10-30T18:17:54.130Z"),
  "createdAt": ISODate("2017-10-30T18:17:54.130Z"),
  "text": "Thanks for joining Elephant Tusk Force!\n\nEvery day, 96 African elephants are killed by ivory poachers. If this continues, they could be extinct by 2025. \n\nThe solution is simple: Flag ivory items on Craigslist to stop elephant poaching.\n\nOnce you have Flagged some Ivory Products, take a pic to prove it! Then text START to share it with us!",
  "direction": "outbound-reply",
  "template": "gambitSignupMenu",
  "conversationId": ObjectId("59f76bf6b7a2df9cd263ead9"),
  "campaignId": 5411,
  "topic": "campaign",
  "broadcastId": null,
  "match": "*",
  "metadata": {
    "requestId": "576875e7-2922-4a2d-9a35-cfbb84bef0bc"
  },
  "attachments": [ ],
  "__v": 0
}
{
  "_id": ObjectId("59f76ccfb7a2df9cd263eae2"),
  "updatedAt": ISODate("2017-10-30T18:17:51.587Z"),
  "createdAt": ISODate("2017-10-30T18:17:51.587Z"),
  "text": "tuskbot",
  "direction": "inbound",
  "template": null,
  "conversationId": ObjectId("59f76bf6b7a2df9cd263ead9"),
  "campaignId": 2299,
  "topic": "support",
  "broadcastId": null,
  "metadata": {
    "requestId": "576875e7-2922-4a2d-9a35-cfbb84bef0bc"
  },
  "attachments": [ ],
  "__v": 0
}
{
  "_id": ObjectId("59f76c1ab7a2df9cd263eae1"),
  "updatedAt": ISODate("2017-10-30T18:14:50.476Z"),
  "createdAt": ISODate("2017-10-30T18:14:50.476Z"),
  "text": "Text back your question and I'll try to get back to you within 24 hrs.\n\nIf you want to continue Two Books Blue Books, text back BOOKBOT",
  "direction": "outbound-reply",
  "template": "memberSupport",
  "conversationId": ObjectId("59f76bf6b7a2df9cd263ead9"),
  "campaignId": 2299,
  "topic": "support",
  "broadcastId": null,
  "match": "q",
  "metadata": {
    "requestId": "6bdbf3e4-8c64-453b-8933-b7c6597e1ba7"
  },
  "attachments": [ ],
  "__v": 0
}
{
  "_id": ObjectId("59f76c1ab7a2df9cd263eae0"),
  "updatedAt": ISODate("2017-10-30T18:14:50.004Z"),
  "createdAt": ISODate("2017-10-30T18:14:50.004Z"),
  "text": "q",
  "direction": "inbound",
  "template": null,
  "conversationId": ObjectId("59f76bf6b7a2df9cd263ead9"),
  "campaignId": 2299,
  "topic": "campaign",
  "broadcastId": null,
  "metadata": {
    "requestId": "6bdbf3e4-8c64-453b-8933-b7c6597e1ba7"
  },
  "attachments": [ ],
  "__v": 0
}

```

**Comment by aaronschachter** [comment]
That first message (the last one in the list) -- the inbound message has a Campaign already set, which is why you got the support message with the Tuskbot keyword. 

There's a bug in this branch from the change of middleware sequence, I read my replies too quickly. When a new Conversation is created (which I do by tweaking my consolebot phone # config var ) and it doesn't have a `campaignId` set, the `supportRequested` template should be returned. the Bug is that `noCampaign` is returned instead. It's a minor one... but I'm going to take another 👀 to see if that's a quick fix. 

membersupport

**Comment by rapala61** [comment]
Actually, I think I omitted something I did before.  I did this before typing `q` again:

With a new number, I typed `q` as per the directions, but got a "Sorry, I'm not sure how to respond to that..." so I typed `MENU` after that, then answered `N` to the campaign Consolebot offered me.

**Comment by aaronschachter** [comment]
No prob! Yup, that's the bug. The MENU command will set the Conversation `campaignId` to the random Campaign that was just pitched. Thanks for testing! Found the bug and going to update shortly.

**Comment by aaronschachter** [comment]
Updated and tested locally.

**Pull request merged**
